service: authorization-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  basicAuthorizer:
    handler: functions/basicAuthorizer/index.handler
    environment:
      KuksovskyiA: ${env:KuksovskyiA}

