service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1


  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::uploaded-data-bucket"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::uploaded-data-bucket/*"

functions:
  importProductsFile:
    handler: functions/importProductsFile/index.handler
    events:
      - http:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors:
            origin: '*'
          authorizer:
            arn: arn:aws:lambda:eu-west-1:645756223154:function:authorization-service-dev-basicAuthorizer
            name: authorization-service-dev-basicAuthorizer

  importFileParser:
    handler: functions/importFileParser/index.handler
    events:
      - s3:
          bucket: uploaded-data-bucket
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    AuthorizerApiGatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId: "dbmwkl2fzl"
